server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-monitoring:3100/loki/api/v1/push
    batchwait: 1s         # Maximum wait time before sending a batch (default: 1s)
    batchsize: 1048576    # Maximum batch size in bytes (default: 1,048,576 = 1MB)

scrape_configs:
  - job_name: dotcms-logs
    static_configs:
      - targets: ['localhost']
        labels:
          component: dotcms
          job: all
          __path__: /var/log/dotcms/*.log