server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:8088/loki/api/v1/push

scrape_configs:
  - job_name: nginx-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log
